### ISSUE TITLE
add a stateful api client for ease of use.

### ISSUE THREAD

**Issue by piusalfred** [piusalfred/whatsapp#18]
@bcmmbaga  and @Hopertz you wanted something like this?

https://github.com/piusalfred/whatsapp/blob/cbe96e3c5261330c4b9d3dd63bd6678f5ea6094d/whatsapp.go#L75-L288

**Comment by bcmmbaga** [comment]
@piusalfred Yes, that is exactly what I had in mind.

**Comment by bcmmbaga** [comment]
@piusalfred May we prioritize the merging of this before moving on to other feature implementations?

**Comment by piusalfred** [comment]
> @piusalfred May we prioritize the merging of this before moving on to other feature implementations?

sounds good @bcmmbaga
